# 服务器配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8080
  tomcat:
    # tomcat的URI编码
    uri-encoding: utf-8
  # 应用访问路径
  servlet:
    context-path: /

# 图像存储路径
image:
  infraredDirectoryOnWin: G:/test/infrared
  ultrasoundDirectoryOnWin: G:/test/ultrasound/
  infraredDirectoryOnLinux: /tmp/vein_scan_dms/infrared/
  ultrasoundDirectoryOnLinux: /tmp/vein_scan_dms/ultrasound/

# Spring配置
spring:
  application:
    name: vein_scan_dms_api
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8

  servlet:
    multipart:
      enabled: true
      #单个文件大小限制
      max-file-size: 10MB
      #请求总文件大小限制
      max-request-size: 100MB
  # redis 配置
  redis:
    # 地址，默认localhost
    host: localhost
    # 端口，默认6379
    port: 6379
    password:

# mybatis-plus配置
mybatis-plus:
  # MyBatis 配置文件位置
  config-location: classpath:mybatis/mybatis-config.xml
  # MyBatis Mapper 所对应的 XML 文件位置，
  mapper-locations: classpath:mybatis/**/*Mapper.xml
  # 配置实体类所在位置
  type-aliases-package: hiram.**.pojo.**

token:
  header: Authorization
  secret: hiram
  expire-time: 1440

jasypt:
  encryptor:
    password: hiram